### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by mikepenz** [DooieNinja/PokeSweep#1]
Thanks for mentioning me, and letting people know that you use my libs in your application. 

I have downloaded it and tested it and came to a few small improvements. 

Currently you can select items in the drawer which will launch an activity, or do not change the content view (like the switch  for active hunt mode) 
I recommend that you add `.withSelectable(false)` to those items, as shown here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L118
(So those are not selected after closing the activity which was opened)

The pokeball icon should be in black when the normal theme  is used.

The `ActionBarDrawerToggle` should be in white when using the normal theme. You can achieve this by setting the theme on the `Toolbar`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L13

**Comment by DooieNinja** [comment]
@mikepenz Thanks for the suggestions.  I've included all of them in update 1.0.7.
